# Generated by Django 5.0.3 on 2025-05-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
