# Generated by Django 5.0.3 on 2025-05-19 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_gasto_activo_ingreso_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('ingreso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finanzas.ingreso')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_Final', models.DateTimeField()),
            ],
            bases=('finanzas.ingreso',),
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.frecuencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
