# Generated by Django 5.0.3 on 2025-05-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_gasto_usuario_alter_gastofijo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gastofijo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='objetivosfinancieros',
            name='actual',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='objetivosfinancieros',
            name='meta',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
